config/routes.rb
Rails.application.routes.draw do
  #get 'bienvenido/index'
  resources :articulos
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'bienvenido#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
	def new
	end
end

app/controllers/bienvenido_controller.rb
class BienvenidoController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/bienvenido_helper.rb
module BienvenidoHelper
end

app/views/articulos/new.html.erb
<h1>Nuevo articulo</h1>
<%= form_for :articulo, url: articulos_path do |f| %>
  <p>
    <%= f.label :titular %><br>
    <%= f.text_field :titular %>
  </p>
 
  <p>
    <%= f.label :contenido %><br>
    <%= f.text_area :contenido %>
  </p>
 
  <p>
    <%= f.submit 'Guardar Artículo' %>
  </p>
<% end %>

app/views/bienvenido/index.html.erb
<h1>Hola, Rails!</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hello</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>